### ISSUE TITLE
Please add sample of processed input training data after step 1

### ISSUE THREAD

**Issue by ahalota** [ankitkariryaa/An-unexpectedly-large-count-of-trees-in-the-western-Sahara-and-Sahel#5]
Could you add a sample folder of what the output from [1-Preprocessing.ipynb](https://github.com/ankitkariryaa/An-unexpectedly-large-count-of-trees-in-the-western-Sahara-and-Sahel/blob/master/notebooks/1-Preprocessing.ipynb) would look like?
I'm trying to adapt this code to my own dataset that is a bit different so seeing what the end result of step 1 is would be helpful.

**Comment by ankitkariryaa** [comment]
I have added the samples of the annotation files and the boundary files generated after the Preprocessing steps. 
You can view the generated images in the notebook using the following code: 
```
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

img = Image.open('file_path_to_image.png')
read_img = np.array(img)
plt.imshow(read_img)
```
